// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9uDpIFxPdutL7y8l3F6owbr0Mvy_wWUo',
    appId: '1:540929459861:web:231ade76e4eb3ea000bd9c',
    messagingSenderId: '540929459861',
    projectId: 'robotoy-d2d86',
    authDomain: 'robotoy-d2d86.firebaseapp.com',
    storageBucket: 'robotoy-d2d86.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsuL3tu43AGwRMERNEHrhMUYoewF96NU4',
    appId: '1:540929459861:android:96dd165ed6600c8100bd9c',
    messagingSenderId: '540929459861',
    projectId: 'robotoy-d2d86',
    storageBucket: 'robotoy-d2d86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFrBlXDKZTjbXx7cTB2n_bgOvB0ts5qXk',
    appId: '1:540929459861:ios:808b314226130ed900bd9c',
    messagingSenderId: '540929459861',
    projectId: 'robotoy-d2d86',
    storageBucket: 'robotoy-d2d86.firebasestorage.app',
    iosBundleId: 'com.example.robotoyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFrBlXDKZTjbXx7cTB2n_bgOvB0ts5qXk',
    appId: '1:540929459861:ios:808b314226130ed900bd9c',
    messagingSenderId: '540929459861',
    projectId: 'robotoy-d2d86',
    storageBucket: 'robotoy-d2d86.firebasestorage.app',
    iosBundleId: 'com.example.robotoyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9uDpIFxPdutL7y8l3F6owbr0Mvy_wWUo',
    appId: '1:540929459861:web:47ceb4b00d33de7e00bd9c',
    messagingSenderId: '540929459861',
    projectId: 'robotoy-d2d86',
    authDomain: 'robotoy-d2d86.firebaseapp.com',
    storageBucket: 'robotoy-d2d86.firebasestorage.app',
  );
}
